#!/usr/bin/env bash
# Build the iOS release and upload it to App Store Connect in one step.
# Same flow and App Store Connect key as runq/apps/mobile/scripts/release-ios.sh,
# adapted for Expo: ios/ is generated by `expo prebuild` (gitignored), so it is
# regenerated from app.json before every build. Version and build number live
# in app.json (expo.version, expo.ios.buildNumber).
#
# Per-machine requirement is the private key:
#     ~/.appstoreconnect/private_keys/AuthKey_YL686HH2SA.p8
# (backup in Dropbox/Certificates/runq/). Override per-run with
#     ASC_KEY_ID=XXXXXXXXXX ASC_ISSUER_ID=<uuid> ./scripts/release-ios.sh
#
# Run from apps/mobile/:
#   ./scripts/release-ios.sh                 # build + upload
#   ./scripts/release-ios.sh --build-only    # stop after the .ipa
#   ./scripts/release-ios.sh --upload-only   # upload the last build again
#   ./scripts/release-ios.sh --build-number 42

set -euo pipefail

ASC_KEY_ID="${ASC_KEY_ID:-YL686HH2SA}"
ASC_ISSUER_ID="${ASC_ISSUER_ID:-c537aebb-3f16-4fb3-9faa-335586aa73b6}"
TEAM_ID="QBLZB22TU6"

BUILD_DIR="ios/build/release"
ARCHIVE="$BUILD_DIR/Martly.xcarchive"
IPA_DIR="$BUILD_DIR/ipa"
BUILD=1
UPLOAD=1
BUILD_NUMBER=""

die() { echo "release-ios: $*" >&2; exit 1; }
step() { printf '\n\033[1m▸ %s\033[0m\n' "$*"; }

while [[ $# -gt 0 ]]; do
  case "$1" in
    --build-only)  UPLOAD=0; shift ;;
    --upload-only) BUILD=0; shift ;;
    --build-number)
      [[ $# -ge 2 ]] || die "--build-number needs a value"
      BUILD_NUMBER="$2"; shift 2 ;;
    -h|--help) sed -n '2,18p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) die "unknown option: $1 (try --help)" ;;
  esac
done

[[ -f app.json && -f package.json ]] || die "run this from apps/mobile/"

# ── Preflight ────────────────────────────────────────────────────────────
KEY_FILE="$HOME/.appstoreconnect/private_keys/AuthKey_${ASC_KEY_ID}.p8"
[[ -f "$KEY_FILE" ]] || die "no API key at $KEY_FILE
  Download the .p8 from App Store Connect and save it there."
[[ -f GoogleService-Info.plist ]] || die "missing GoogleService-Info.plist"
[[ -f .env.production ]] || die "missing .env.production (EXPO_PUBLIC_API_URL for release builds)"
PROD_API_URL=$(grep -m1 '^EXPO_PUBLIC_API_URL=' .env.production | cut -d= -f2-)
[[ "$PROD_API_URL" == https://* ]] || die "EXPO_PUBLIC_API_URL in .env.production must be an https URL"

VERSION=$(node -p "require('./app.json').expo.version")
BUILD_NUMBER="${BUILD_NUMBER:-$(node -p "require('./app.json').expo.ios.buildNumber")}"
echo "release-ios: ${VERSION} (${BUILD_NUMBER})"

# The API key also authenticates -allowProvisioningUpdates, so automatic
# signing can create/download profiles without an Xcode login.
AUTH_ARGS=(-allowProvisioningUpdates
  -authenticationKeyPath "$KEY_FILE"
  -authenticationKeyID "$ASC_KEY_ID"
  -authenticationKeyIssuerID "$ASC_ISSUER_ID")

# ── Build ────────────────────────────────────────────────────────────────
if [[ "$BUILD" == 1 ]]; then
  step "Regenerating ios/ from app.json"
  CI=1 npx expo prebuild -p ios

  step "Archiving"
  rm -rf "$BUILD_DIR"
  xcodebuild archive \
    -workspace ios/Martly.xcworkspace -scheme Martly \
    -configuration Release -destination "generic/platform=iOS" \
    -archivePath "$ARCHIVE" \
    DEVELOPMENT_TEAM="$TEAM_ID" CURRENT_PROJECT_VERSION="$BUILD_NUMBER" \
    "${AUTH_ARGS[@]}" -quiet
  /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" \
    "$ARCHIVE/Products/Applications/Martly.app/Info.plist"

  # The API URL is inlined into the JS bundle at build time; never ship one that points at a dev machine
  BUNDLE="$ARCHIVE/Products/Applications/Martly.app/main.jsbundle"
  grep -q "$PROD_API_URL" "$BUNDLE" || die "release bundle does not contain $PROD_API_URL"
  if grep -qE "https?://(localhost|127\.0\.0\.1|192\.168\.|10\.[0-9]+\.)" "$BUNDLE"; then
    die "release bundle references a local/LAN address — check apps/mobile/.env.production"
  fi
  echo "release-ios: bundle talks to $PROD_API_URL"

  step "Exporting IPA"
  EXPORT_OPTIONS="$BUILD_DIR/ExportOptions.plist"
  cat > "$EXPORT_OPTIONS" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>method</key><string>app-store-connect</string>
  <key>teamID</key><string>${TEAM_ID}</string>
  <key>signingStyle</key><string>automatic</string>
</dict></plist>
PLIST
  xcodebuild -exportArchive -archivePath "$ARCHIVE" \
    -exportPath "$IPA_DIR" -exportOptionsPlist "$EXPORT_OPTIONS" \
    "${AUTH_ARGS[@]}"
fi

IPA="$IPA_DIR/Martly.ipa"
[[ -f "$IPA" ]] || die "no .ipa at $IPA — run without --upload-only to build one first"

# ── Validate, then upload ────────────────────────────────────────────────
if [[ "$UPLOAD" == 1 ]]; then
  step "Validating"
  xcrun altool --validate-app -f "$IPA" -t ios \
    --apiKey "$ASC_KEY_ID" --apiIssuer "$ASC_ISSUER_ID" \
    || die "validation failed — nothing was uploaded"

  step "Uploading to App Store Connect"
  xcrun altool --upload-app -f "$IPA" -t ios \
    --apiKey "$ASC_KEY_ID" --apiIssuer "$ASC_ISSUER_ID"

  step "Done"
  echo "Uploaded ${VERSION} (${BUILD_NUMBER}). Shows up in TestFlight after 5-15 min."
  echo "Bump expo.ios.buildNumber in app.json before the next release."
else
  step "Built $IPA"
  echo "Upload it with: $0 --upload-only"
fi
