/**
 * Backfill Product.tags with short attribute tags generated by Claude Haiku.
 *
 * Usage: cd apps/api && npx tsx scripts/backfill-product-tags.ts [--dry-run] [--limit N] [--force]
 * Products with non-empty tags are skipped unless --force is given.
 */

import dotenv from "dotenv";
dotenv.config({ override: true });

import Anthropic from "@anthropic-ai/sdk";
import { PrismaClient } from "../generated/prisma/index.js";

const MODEL = "claude-haiku-4-5-20251001";
const BATCH_SIZE = 25;
const MAX_TAGS = 4;

const SYNONYMS: Record<string, string> = {
  unpolish: "unpolished",
  "non-polished": "unpolished",
  "un-polished": "unpolished",
  sugarfree: "sugar-free",
  "no-sugar": "sugar-free",
  "zero-sugar": "sugar-free",
  "no-added-sugar": "sugar-free",
  "organically-grown": "organic",
  "pesticide-free": "pesticide-free",
  "no-pesticide": "pesticide-free",
  "chemical-free": "pesticide-free",
  glutenfree: "gluten-free",
  lowfat: "low-fat",
  "reduced-fat": "low-fat",
  "cold-press": "cold-pressed",
  coldpressed: "cold-pressed",
  "family-size": "family-pack",
  "value-pack": "family-pack",
  "whole-grain": "whole",
  wholegrain: "whole",
  "premium-quality": "premium",
};

const BANNED = new Set(["food", "product", "healthy", "tasty", "fresh", "natural", "quality", "pack", "new"]);

const SYSTEM_PROMPT = `You tag grocery products for an Indian grocery store with short attribute tags that shoppers filter by within an aisle (like Blinkit's "Organic", "Unpolished", "Sugar free" tabs).

Rules:
- Return ONLY a JSON object mapping each product id to an array of 0 to ${MAX_TAGS} tags. No prose.
- Tags are lowercase, 1-2 words, hyphen for compounds (sugar-free, cold-pressed, pesticide-free).
- Only attributes that distinguish products WITHIN the same aisle, e.g. organic, unpolished, whole, split, roasted, low-fat, sugar-free, gluten-free, premium, family-pack, cold-pressed, fortified, multigrain, high-protein, vegan, unsalted, unsweetened, instant, stone-ground, sun-dried, raw, wild.
- Only when the attribute is EXPLICITLY stated in the product name or description (the word or a direct equivalent). Do NOT infer from brand reputation or general knowledge: never add vegan, gluten-free, premium, fortified, high-protein, sugar-free etc. unless the text says so. Most products should get 0-2 tags; an empty array is common and correct. Never tag non-food items (toiletries, cleaning, personal care) with food attributes.
- NEVER use brand names, category/subcategory names, generic words (food, product, healthy, tasty, fresh, natural), sizes/weights, or the product noun itself (e.g. no "toor-dal" for toor dal).
- Prefer re-using common tags from the vocabulary above so tags repeat across products.`;

interface ProductRow {
  id: string;
  name: string;
  description: string | null;
  tags: string[];
  brand: { name: string } | null;
  subcategory: { name: string } | null;
}

type TagMap = Map<string, string[]>;

function parseArgs() {
  const args = process.argv.slice(2);
  const limitIdx = args.indexOf("--limit");
  return {
    dryRun: args.includes("--dry-run"),
    force: args.includes("--force"),
    limit: limitIdx >= 0 ? Number(args[limitIdx + 1]) : undefined,
  };
}

export function normaliseTag(raw: unknown): string | null {
  if (typeof raw !== "string") return null;
  const tag = raw.toLowerCase().trim().replace(/[\s_]+/g, "-").replace(/[^a-z0-9-]/g, "").replace(/^-+|-+$/g, "");
  const mapped = SYNONYMS[tag] ?? tag;
  if (mapped.length < 3 || mapped.length > 24 || BANNED.has(mapped)) return null;
  return mapped.split("-").length > 2 ? null : mapped;
}

function normaliseTags(raw: unknown): string[] {
  if (!Array.isArray(raw)) return [];
  const tags = raw.map(normaliseTag).filter((t): t is string => t !== null);
  return [...new Set(tags)].slice(0, MAX_TAGS);
}

function buildPayload(batch: ProductRow[]) {
  return batch.map((p) => ({
    id: p.id,
    name: p.name,
    brand: p.brand?.name ?? "",
    subcategory: p.subcategory?.name ?? "",
    description: (p.description ?? "").slice(0, 200),
  }));
}

function parseModelOutput(text: string, batch: ProductRow[]): TagMap {
  const match = text.match(/\{[\s\S]*\}/);
  if (!match) throw new SyntaxError("no JSON object in model output");
  const parsed: unknown = JSON.parse(match[0]);
  if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
    throw new SyntaxError("model output is not an object");
  }
  const validIds = new Set(batch.map((p) => p.id));
  const result: TagMap = new Map();
  for (const [id, raw] of Object.entries(parsed)) {
    if (validIds.has(id)) result.set(id, normaliseTags(raw));
  }
  return result;
}

async function requestTags(client: Anthropic, batch: ProductRow[]): Promise<TagMap> {
  const response = await client.messages.create({
    model: MODEL,
    max_tokens: 2500,
    system: SYSTEM_PROMPT,
    messages: [{ role: "user", content: `Products:\n${JSON.stringify(buildPayload(batch))}\n\nJSON object:` }],
  });
  const block = response.content[0];
  return parseModelOutput(block.type === "text" ? block.text : "", batch);
}

async function tagBatch(client: Anthropic, batch: ProductRow[]): Promise<TagMap | null> {
  for (let attempt = 1; attempt <= 2; attempt++) {
    try {
      return await requestTags(client, batch);
    } catch (err) {
      if (!(err instanceof SyntaxError)) throw err;
      console.warn(`  batch parse failed (attempt ${attempt}): ${err.message}`);
    }
  }
  console.warn("  skipping batch");
  return null;
}

function printFrequencies(all: TagMap, products: ProductRow[], samples: number) {
  const freq = new Map<string, number>();
  for (const tags of all.values()) for (const t of tags) freq.set(t, (freq.get(t) ?? 0) + 1);
  const sorted = [...freq.entries()].sort((a, b) => b[1] - a[1]);
  const tagged = [...all.values()].filter((t) => t.length > 0).length;
  console.log(`\nTagged ${tagged} / ${all.size} processed products; ${sorted.length} distinct tags`);
  console.table(sorted.slice(0, 60).map(([tag, count]) => ({ tag, count })));
  if (samples === 0) return;
  console.log("\nSample products:");
  for (const p of products.filter((p) => all.get(p.id)?.length).slice(0, samples)) {
    console.log(`  ${p.name} (${p.subcategory?.name ?? "-"}) -> [${all.get(p.id)!.join(", ")}]`);
  }
}

async function loadProducts(prisma: PrismaClient, force: boolean, limit?: number): Promise<ProductRow[]> {
  const products = await prisma.product.findMany({
    select: {
      id: true, name: true, description: true, tags: true,
      brand: { select: { name: true } },
      subcategory: { select: { name: true } },
    },
    orderBy: { id: "asc" },
    take: limit,
  });
  return force ? products : products.filter((p) => p.tags.length === 0);
}

async function writeBatch(prisma: PrismaClient, tags: TagMap) {
  await prisma.$transaction(
    [...tags.entries()].map(([id, t]) => prisma.product.update({ where: { id }, data: { tags: t } })),
  );
}

async function main() {
  const { dryRun, force, limit } = parseArgs();
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) throw new Error("ANTHROPIC_API_KEY missing in apps/api/.env");
  const prisma = new PrismaClient();
  const client = new Anthropic({ apiKey });

  const products = await loadProducts(prisma, force, limit);
  console.log(`${products.length} products to process${dryRun ? " (dry run)" : ""}`);

  const all: TagMap = new Map();
  for (let i = 0; i < products.length; i += BATCH_SIZE) {
    const batch = products.slice(i, i + BATCH_SIZE);
    const tags = await tagBatch(client, batch);
    console.log(`batch ${i / BATCH_SIZE + 1}/${Math.ceil(products.length / BATCH_SIZE)}: ${tags ? "ok" : "skipped"}`);
    if (!tags) continue;
    tags.forEach((t, id) => all.set(id, t));
    if (!dryRun) await writeBatch(prisma, tags);
  }

  printFrequencies(all, products, dryRun ? 20 : 0);
  await prisma.$disconnect();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
